version: "3.8"

services:
  web-server:
    image: nginx:latest
    container_name: web-server-container
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - my_network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - "9000:9000"
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge
