version: "3.8"
services:
  web-server:
    image: nginx:latest
    container_name: web-server-container
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - "9000:9000"
  db:
    image: postgres:alpine
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345